engines:
  duplication:
    enabled: true
    config:
      languages:
        - python:
            mass_threshold: 50
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "src/codeschool/**.py"
exclude_paths:
  - src/codeschool/**/migrations/